name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Run build script
        run: npm run build
      - name: Determine Tag Name
        id: increment_tag
        run: |
          echo "::set-output name=tag_name::$(date +v%Y%m%d)"
        shell: bash
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.increment_tag.outputs.tag_name }}
          release_name: Release ${{ steps.increment_tag.outputs.tag_name }}
          draft: false
          prerelease: false
          commitish: ${{ github.sha }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
